apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argo-system
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: For Argo.
  sourceRepos:
    - "https://github.com/ZhongKuo0228/pipeline_infra.git"
  destinations:
    - namespace: "default"
      server: "https://kubernetes.default.svc"
