name: Terraform apply

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  # notify-discord:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Send workflow URL to Discord
  #       run: |
  #         curl -H "Content-Type: application/json" \
  #         -X POST \
  #         -d '{"content": "Terraform Apply 準備! 請協助 Approve: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}' \
  #         ${{ secrets.DISCORD_WEBHOOK_URL }}

  # terraform_plan:
  #   needs: notify-discord
  #   runs-on: ubuntu-latest
  #   permissions:
  #     pull-requests: write
  #   defaults:
  #     run:
  #       working-directory: src
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #     - name: Create SSH Key File
  #       run: |
  #         echo "${{ secrets.SSH_PUBLIC_KEY }}" > terraform-ssh-key.pub
  #       shell: bash
  #     - name: Init Terraform
  #       run: terraform init
  #     - name: Validate_Terraform
  #       run: terraform validate
  #     - name: Plan_Terraform
  #       run: terraform plan

  terraform_apply:
    # needs: terraform_plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create SSH Key File
        run: |
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > terraform-ssh-key.pub
        shell: bash
      - name: Init Terraform
        run: terraform init
      - name: Terraform Apply
        run: |
          terraform apply -auto-approve
      - name: Set Output
        run: echo "::set-output name=instance_ip::$(terraform output -raw INSTANCE_IP)"

  deploy:
    needs: terraform_apply
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup SSH and execute commands on jump server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ needs.terraform_apply.outputs.instance_ip }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            touch ${{ github.run_id }}
