name: PR Check Terraform Validate And Plan

on:
  pull_request:
    branches:
      - '**'
    paths:
      - 'src/**'

jobs:
  terraform_plan:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    permissions:
      pull-requests: write
    defaults:
      run:
        working-directory: src
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create SSH Key File
        run: |
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > terraform-ssh-key.pub
        shell: bash
      - name: Init Terraform
        run: terraform init
      - name: Validate_Terraform
        run: terraform validate
      - name: Plan_Terraform
        run: terraform plan
      - name: Show Plan
        id: showplan
        run: |
          terraform plan -no-color > plan.txt
      - name: Upload Plan Output as PR Comment
        uses: mshick/add-pr-comment@v2
        with:
          message-path: |
            ${{ github.workspace }}/src/plan.txt