name: PR Check Terraform Validate And Plan

on:
  pull_request:
    branches:
      - '**'
    paths:
      - 'src/**'

jobs:
  terraform_plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Init Terraform
        run: terraform init
        working-directory: src
      - name: Validate_Terraform
        run: terraform validate
        working-directory: src
      - name: Plan_Terraform
        run: terraform plan
        working-directory: src
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Show Plan
        id: showplan
        run: terraform plan -no-color > plan.json
        working-directory: src
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Upload Plan Output as PR Comment
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const planOutput = fs.readFileSync('${{ github.workspace }}/src/plan.json', 'utf8');
            const issue_number = context.issue.number;
            github.rest.issues.createComment({
              ...context.repo,
              issue_number: issue_number,
              body: '## Terraform Plan Output\n' + '```' + planOutput + '```'
            });
