name: PR Check Terraform Validate And Plan

on:
  pull_request:
    branches:
      - '**'
    paths:
      - 'src/**'

jobs:
  terraform_plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Init Terraform
        run: terraform init
        working-directory: src
      - name: Validate_Terraform
        run: terraform validate
        working-directory: src
      - name: Plan_Terraform
        run: terraform plan
        working-directory: src
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Show Plan
        id: showplan
        run: |
          output=$(terraform plan -no-color)
        working-directory: src
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Upload Plan Output as PR Comment
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            $output